/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeeklyIndexImport } from './routes/weekly/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeeklyIndexRoute = WeeklyIndexImport.update({
  id: '/weekly/',
  path: '/weekly/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/weekly/': {
      id: '/weekly/'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/weekly': typeof WeeklyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/weekly': typeof WeeklyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/weekly/': typeof WeeklyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/weekly'
  id: '__root__' | '/' | '/weekly/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeeklyIndexRoute: typeof WeeklyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeeklyIndexRoute: WeeklyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/weekly/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/weekly/": {
      "filePath": "weekly/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
